spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/impensa_server_spring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDIALECT
security:
  secret-key: barbimbarbimbarbimbarbimbarbimbarbimbarbimbarbimbarbimbarbimbarbimbarbimbarbimbarbimbarbimbarbimbarbimbarbim
